### PR TITLE
[trello.com/c/aIVBEdjR] Improve coin tx sending algorithm

### LINKED ISSUE #930: [Task] Verify / Update coin Transaction sending algorithm
### Summary

Verify and, if required, update the coin transaction sending algorithm and related status handling logic in the iOS client.

### Details

Scope:

- Coin transaction sending algorithm  
- Coin transaction status checks  
- Synchronization of coin transaction statuses between:
  - Chat screen  
  - Chat list  
  - Transaction details screen  

The logic must strictly validate network connectivity and availability of coin nodes before performing status checks or retries, in order to prevent incorrect status transitions (e.g., false `Failed`).

Implementation must align with:

- https://github.com/orgs/Adamant-im/discussions/31  
- https://github.com/orgs/Adamant-im/discussions/30  

### Motivation

Current behavior may lead to incorrect transaction status transitions when:

- The device is offline  
- There is no access to coin nodes  
- Node requests fail due to connectivity issues rather than real transaction failure  

In such cases, the app may:

- Exhaust retry / check attempts  
- Incorrectly mark transactions as `Failed`  
- Desynchronize transaction state between Chat, Chat list, and Tx details  

This results in:

- Misleading UX  
- Loss of user trust  
- Inconsistent transaction state across UI layers  

The goal is to make transaction status logic deterministic, network-aware, and consistent across all UI components.

### Details

1. Coin Transaction Sending Algorithm

- Review full sending lifecycle:
  - Local creation
  - Broadcast to coin node
  - Initial pending state
  - Confirmation detection
- Ensure no premature status transitions.
- Confirm retry logic is safe and bounded.
- Verify behavior when:
  - Node temporarily unavailable
  - Network unstable
  - App is backgrounded / relaunched

2. Coin Transaction Status Checks

- Status checks must only be executed if:
  - Network connection is available  
  - Coin node is reachable and responsive  
- If network or nodes are unavailable:
  - Do not decrement retry counters
  - Do not transition status to `Failed`
  - Preserve current state (e.g., `Pending`)
- Clearly distinguish between:
  - Logical failure (rejected / invalid tx)
  - Network failure (temporary unavailability)

3. Status Synchronization Across UI

Ensure strict consistency between:

- Chat screen (inline message state)
- Chat list (last message preview state)
- Transaction details screen (full status + metadata)

Requirements:

- Single source of truth for tx status.
- No duplicated state logic in different UI layers.
- UI must react to state updates via unified state model.
- No scenario where:
  - Chat shows `Failed`
  - Tx details show `Pending`
  - Or vice versa

4. Retry / Attempt Handling

- Validate maximum number of checks.
- Retry counter must:
  - Be paused when offline.
  - Resume only when connectivity and nodes are available.
- Ensure app restarts do not reset or corrupt retry state.

5. Alignment with Discussions

Ensure implementation matches decisions and expectations described in:

- https://github.com/orgs/Adamant-im/discussions/31  
- https://github.com/orgs/Adamant-im/discussions/30  

Particularly regarding:

- Failure conditions
- Status transitions
- Node validation logic
- UX expectations for pending / failed states

### Notes

- The key constraint: never mark a transaction as `Failed` purely because of missing connectivity.
- Network and node validation must be explicit and reliable.
- UX should clearly reflect:
  - Pending (awaiting confirmation)
  - Confirmed
  - Failed (only if logically failed)

This task impacts core trust in coin transfers and must be handled conservatively.

### Verification

Test scenarios must include:

1. Send coin transaction while online → confirm correct pending → confirmed transition.
2. Send transaction, then disable network:
   - Status must remain pending.
   - No retry exhaustion.
3. Node temporarily unavailable:
   - No immediate failure.
4. Restore connectivity:
   - Status correctly revalidated.
5. Compare status consistency across:
   - Chat
   - Chat list
   - Tx details screen
6. Relaunch app mid-pending:
   - State restored correctly.
7. Confirm no false `Failed` transitions in logs.

Successful verification means:

- Deterministic status behavior
- No desynchronization between screens
- No false-negative transaction failures

Checklist:

- [ ] Review existing coin tx sending flow
- [ ] Audit status transition logic
- [ ] Implement network + node availability guard before checks
- [ ] Prevent false `Failed` due to connectivity issues
- [ ] Unify tx status source of truth
- [ ] Sync Chat, Chat list, and Tx details
- [ ] Validate retry counter behavior
- [ ] Test behavior on:
  - Airplane mode
  - Node downtime
  - App restart
  - Background → foreground
- [ ] Confirm alignment with discussions 30 and 31

## Issues found while testing

See in comments below.

- [ ] Wrong tx status (Received in chat USDT from another account)
- [ ] Crashes while checking txs with triggering Airplane mode on device
- [ ] Sending ADM in chat in Airplane mode (with VPN used)

### PR DESCRIPTION
**Pull request by Lainaaa**

### CODE REVIEW

File: Adamant/Models/BTCRawTransaction.swift [hunk 1]
```diff
@@ -27,15 +27,14 @@ struct BTCRawTransaction {
 
     func asBtcTransaction<T: BaseBtcTransaction>(_ as: T.Type, for address: String, blockId: String? = nil) -> T {
         // MARK: Known values
-        let confirmationsValue: String?
-        let transactionStatus: TransactionStatus
+        var confirmationsValue: String? = nil
```
Comment (vovameister) [inline Adamant/Models/BTCRawTransaction.swift:30]: = nil - unnecessary change

File: Adamant/Modules/Wallets/Bitcoin/BtcWalletService+RichMessageProviderWithStatusCheck.swift [hunk 2]
```diff
@@ -44,6 +44,8 @@ extension BtcWalletService {
         transaction: CoinTransaction,
         btcTransaction: BtcTransaction
     ) async -> TransactionStatus {
+        // Before we already stored another status in RawBtcTransactionResponse.asBtcTransaction(_:for:height:).
```
Comment (vovameister) [inline Adamant/Modules/Wallets/Bitcoin/BtcWalletService+RichMessageProviderWithStatusCheck.swift:47]: what's the point of your comment if you haven't changed anything in this method

Comment (Lainaaa) [reply Adamant/Modules/Wallets/Bitcoin/BtcWalletService+RichMessageProviderWithStatusCheck.swift:47]: To make it clear.
Honestly, I don't fully understand your question, are you against commenting existed code?

**Review by vovameister — APPROVED** [review]

File: Adamant/Modules/Wallets/Bitcoin/BtcWalletService+RichMessageProviderWithStatusCheck.swift (hunk 2 above)
Comment (vovameister) [reply Adamant/Modules/Wallets/Bitcoin/BtcWalletService+RichMessageProviderWithStatusCheck.swift:47]: I think it's better to write a description in PR than to write comments for code that you haven't made any changes to
