### PR TITLE
[trello.com/c/pRsTtPYQ] fix reply + file sending

### LINKED ISSUE #921: [Bug, UX/UI] Incorrect display of unavailable attachments in chat
### Summary

When a chat includes messages with unavailable attachments, they are displayed incorrectly.

### Steps to reproduce

1. Open a chat containing messages with unavailable attachments (chat with ..55297 in test account)
2. Tap on the **red circle with arrow** icon near the message
3. Observe the incorrect display/behavior

### Expected behavior

- On tap, Icon behavior should follow this sequence:
  - **Red circle with arrow** → **Clock (downloading)** → **Red circle with arrow** (if download fails again)  
- Show a **temporary popup** (Popup should disappear automatically after a short delay) if downloading fails again
  - Two kinds of message depending whether all files unavailable or some files:
    - All files
      - `Files are not currently accessible`
      - `Файлы недоступны`
    - Some files
      - `Some files are not currently accessible`
      - `Некоторые файлы недоступны`
  - Style:
Image

- Add **vibration feedback** (“Error” type)

### Actual behavior

On "Unavailable icon" tap, Nothing happen

### Screenshots or videos

Image

### Environment

**Platform:** iOS app  
**Version:** Build 3.11.0 (20)

### PR DESCRIPTION
**Pull request by vovameister**

### CODE REVIEW

**Review by Lainaaa — APPROVED** [review]

File: Adamant/Modules/Chat/ViewModel/ChatViewModel.swift [hunk 1]
```diff
@@ -1735,6 +1735,11 @@ extension ChatViewModel {
             return .failed
         }
 
+        if model.content.fileModel.files.contains(where: { $0.isDownloading }),
+           model.content.fileModel.files.contains(where: { $0.file.nonce.isEmpty }) {
```
Comment (Lainaaa) [inline Adamant/Modules/Chat/ViewModel/ChatViewModel.swift]: Could you combine this 2 and avoid unnecessary recalculations

**Review by Lainaaa — CHANGES_REQUESTED** [review]
